// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mexehqylewoaqaadlvuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1leGVocXlsZXdvYXFhYWRsdnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODQ5NjYsImV4cCI6MjA2Njk2MDk2Nn0.ADJZu-nZpvkASGm6LIU6Lv_LG09dGLIGey7LF4drWzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});